// Package manifest describes a pinned upstream data tree: which datasets it
// holds, where each one came from, and what bytes each one must have.
//
// A manifest is the boundary between fetching and generating. The fetcher
// writes one; generation reads only a tree whose manifest verifies, so no
// generated byte can come from a file nobody pinned.
package manifest

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"
)

// Version is the manifest schema this package reads. A tree written by an
// older layout is rejected rather than guessed at.
const Version = 2

// FileName is the manifest's name inside a source tree.
const FileName = "manifest.json"

// sourceRoot is the only upstream directory a dataset may come from. Anything
// else is either a different edition or a path escaping the data tree.
const sourceRoot = "data/pc/"

// revisionLength is the length of a full Git commit hash. A branch or a short
// hash is refused: only a full commit pins a tree.
const revisionLength = 40

// Dataset is one upstream file, its place in the local tree, and its bytes.
type Dataset struct {
	// Name is how generation asks for the dataset, without an extension.
	Name string `json:"name"`
	// File is the dataset's path inside the source tree, relative and slashed.
	File string `json:"file"`
	// SourcePath is where upstream keeps it, under data/pc/.
	SourcePath string `json:"sourcePath"`
	MediaType  string `json:"mediaType"`
	SHA256     string `json:"sha256"`
}

// Manifest describes one pinned source tree.
type Manifest struct {
	ManifestVersion        int       `json:"manifestVersion"`
	Edition                string    `json:"edition"`
	TargetMinecraftVersion string    `json:"targetMinecraftVersion"`
	SourceMinecraftVersion string    `json:"sourceMinecraftVersion"`
	Protocol               int32     `json:"protocol"`
	SourceRepository       string    `json:"sourceRepository"`
	SourceRevision         string    `json:"sourceRevision"`
	License                string    `json:"license"`
	Datasets               []Dataset `json:"datasets"`
}

// SourceVersion returns the upstream version directory a dataset was taken
// from: the segment after data/pc/. It is "1.16.1" for a dataset upstream
// keeps under data/pc/1.16.1.
func (d Dataset) SourceVersion() string {
	rest := strings.TrimPrefix(d.SourcePath, sourceRoot)
	version, _, found := strings.Cut(rest, "/")
	if !found {
		return ""
	}

	return version
}

// Aliased reports whether the dataset came from a directory other than
// version's. An aliased dataset is upstream's decision, not a bug, but
// consumers must be able to see it: a window layout resolved from 1.16.1 is
// nine years old however current the version asking for it.
//
// version is the upstream data directory being fetched, which is not always
// the release name — Java 1.8.9 data lives under data/pc/1.8.
func (d Dataset) Aliased(version string) bool {
	return d.SourceVersion() != version
}

// Dataset returns the named dataset.
func (m *Manifest) Dataset(name string) (Dataset, bool) {
	for _, dataset := range m.Datasets {
		if dataset.Name == name {
			return dataset, true
		}
	}

	return Dataset{}, false
}

// Names returns every dataset name, in manifest order.
func (m *Manifest) Names() []string {
	names := make([]string, 0, len(m.Datasets))
	for _, dataset := range m.Datasets {
		names = append(names, dataset.Name)
	}

	return names
}

// Load reads and validates the manifest in dir. It does not read the datasets
// themselves; call Verify for that.
func Load(dir string) (*Manifest, error) {
	raw, err := os.ReadFile(filepath.Join(dir, FileName))
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}

	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.DisallowUnknownFields()

	var loaded Manifest
	if err := decoder.Decode(&loaded); err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}

	if err := loaded.validate(); err != nil {
		return nil, err
	}

	return &loaded, nil
}

// validate checks the manifest in a fixed order — schema version, edition,
// scalar fields, then datasets in manifest order — so the first error a
// malformed manifest produces does not depend on map iteration.
func (m *Manifest) validate() error {
	if m.ManifestVersion != Version {
		return fmt.Errorf("unsupported manifest version %d, want %d", m.ManifestVersion, Version)
	}
	if m.Edition != "java" {
		return fmt.Errorf("unsupported edition %q", m.Edition)
	}

	for _, field := range []struct {
		name  string
		value string
	}{
		{"targetMinecraftVersion", m.TargetMinecraftVersion},
		{"sourceMinecraftVersion", m.SourceMinecraftVersion},
		{"sourceRepository", m.SourceRepository},
		{"license", m.License},
	} {
		if field.value == "" {
			return fmt.Errorf("%s is required", field.name)
		}
	}

	if m.Protocol <= 0 {
		return fmt.Errorf("protocol %d must be positive", m.Protocol)
	}
	if !isHex(m.SourceRevision, revisionLength) {
		return fmt.Errorf("sourceRevision %q must be a full lowercase commit hash", m.SourceRevision)
	}
	if len(m.Datasets) == 0 {
		return fmt.Errorf("datasets must name at least one file")
	}

	seen := make(map[string]struct{}, len(m.Datasets))
	for _, dataset := range m.Datasets {
		if err := dataset.validate(); err != nil {
			return err
		}
		if _, duplicate := seen[dataset.Name]; duplicate {
			return fmt.Errorf("duplicate dataset %q", dataset.Name)
		}
		seen[dataset.Name] = struct{}{}
	}

	return nil
}

func (d Dataset) validate() error {
	if d.Name == "" {
		return fmt.Errorf("every dataset needs a name")
	}
	if strings.ContainsAny(d.Name, `/\.`) {
		return fmt.Errorf("dataset name %q must not name a path", d.Name)
	}
	if !isLocalPath(d.File) {
		return fmt.Errorf("dataset %s: file %q must be a relative path inside the source tree", d.Name, d.File)
	}
	if !isLocalPath(d.SourcePath) || !strings.HasPrefix(d.SourcePath, sourceRoot) {
		return fmt.Errorf("dataset %s: sourcePath %q must be under %s", d.Name, d.SourcePath, sourceRoot)
	}
	if d.MediaType == "" {
		return fmt.Errorf("dataset %s: mediaType is required", d.Name)
	}
	if !isHex(d.SHA256, sha256.Size*2) {
		return fmt.Errorf("dataset %s: sha256 %q must be 64 lowercase hex characters", d.Name, d.SHA256)
	}

	return nil
}

// Verify reads every dataset in dir, checks its bytes against the manifest,
// and reports any file in the tree the manifest does not name.
func (m *Manifest) Verify(dir string) error {
	recorded := make(map[string]struct{}, len(m.Datasets)+1)
	recorded[FileName] = struct{}{}

	for _, dataset := range m.Datasets {
		recorded[dataset.File] = struct{}{}

		body, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(dataset.File)))
		if err != nil {
			return fmt.Errorf("dataset %s: %w", dataset.Name, err)
		}

		digest := sha256.Sum256(body)
		if hex.EncodeToString(digest[:]) != dataset.SHA256 {
			return fmt.Errorf("dataset %s: %s does not match its recorded checksum", dataset.Name, dataset.File)
		}
	}

	return m.verifyNoExtraFiles(dir, recorded)
}

func (m *Manifest) verifyNoExtraFiles(dir string, recorded map[string]struct{}) error {
	root := os.DirFS(dir)

	return fs.WalkDir(root, ".", func(name string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		if _, ok := recorded[name]; !ok {
			return fmt.Errorf("%s is not recorded in the manifest", name)
		}

		return nil
	})
}

// isLocalPath reports whether name is a relative, slash-separated path that
// stays inside its tree. A path that is not already clean is refused rather
// than cleaned, so what the manifest says is what gets read.
func isLocalPath(name string) bool {
	if name == "" || path.IsAbs(name) || filepath.IsAbs(name) {
		return false
	}
	if strings.ContainsRune(name, '\\') {
		return false
	}

	return path.Clean(name) == name && !strings.HasPrefix(name, "../")
}

func isHex(value string, length int) bool {
	if len(value) != length {
		return false
	}
	for _, r := range value {
		switch {
		case r >= '0' && r <= '9':
		case r >= 'a' && r <= 'f':
		default:
			return false
		}
	}

	return true
}
